#!/bin/bash

echo "Add layer [$1]"
nb=$(grep "^$1$" ./layers_list | wc -l) # C'est moche
if [[ "$nb" == "0" ]]
then
	echo "$1" >> ./layers_list
	LAYERS=$(cat ./layers_list | tr ' ' '\n')
	build-compose
	docker-compose -p $APP_NAME up -d --force-recreate rok4
fi